name: Fetch script's Jsdelivr cache

on:
  push:
    paths:
      - 'tuic.sh'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch script's Jsdelivr cache
        run: |
          curl https://purge.jsdelivr.net/gh/Misaka-blog/tuic-script/tuic.sh